# workflow name
name: Generate builds and release

# on events
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
  
permissions:
  contents: write

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: ''
            name: 'git-ignore'
            compress: 'false'
            dest: 'dist'
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Test
          files: |
            dist/git-ignore-linux-amd64
            dist/git-ignore-darwin-amd64
            dist/git-ignore-windows-amd64.exe
