# workflow name
name: Build go package

# on events
on:
  release:
    types: 
        - created
  workflow_dispatch:

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/386, linux/amd64, darwin/amd64, darwin/arm64, windows/386, windows/amd64'
            package: ''
            name: 'git-ignore'
            compress: 'false'
            dest: 'dist'
